title: "Materiały z lekcji Roblox Studio"
description: "Kody i materiały z zajęć Roblox Studio."
lang: pl
timezone: Europe/Warsaw
url: "https://szymonduda7.github.io"
baseurl: "/lekcja-ak"

exclude:
  - BLUEPRINT-LEKCJI.md
  - README.md
