title: "Materiały z lekcji Roblox Studio"
description: "Kody i materiały z zajęć Roblox Studio."
lang: pl
timezone: Europe/Warsaw
url: "https://lekcja-ak.pl"
baseurl: ""

exclude:
  - BLUEPRINT-LEKCJI.md
  - README.md
